name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: par1kahl
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=556B2F&color_dots=#ebedf0,#8B6848,#a08060,#556B2F,#1B3A5C
            dist/github-contribution-grid-snake-dark.svg?color_snake=556B2F&color_dots=#161b22,#8B6848,#a08060,#556B2F,#1B3A5C
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
